driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: 'ubuntu'
    driver_plugin: docker
    driver:
      use_sudo: false
      image: ubuntu:16.04
suites:
  - name: default
    run_list:
      - recipe[sa-nginx::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
